### PR TITLE
Code review pull request

### PR DESCRIPTION
**Pull request by MiguelDP4**
- Created a header divided in two, and created a navigation bar inside
- Created the HTML structure
- Used bootstrap framework to style the layout of the website

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Your work is remarkable! :rocket: 
Wow @MiguelDP4, you have really pulled it off. I couldn't tell much difference between your project and the original. There are just a few tiny details you need to iron out on the screen sizes from 425px and below, please consider my comments below :100: 

#### Responsiveness
There were a few issues with the responsiveness, particularly at 425px and 320px. Please see screenshots of some of the issues encountered but do a full scan through all sections as I didn't attach them all. 

* First
screenshot

* Second
screenshot

In the first image, you'd notice the `sign in` button in the navigation colliding with the logo, please resolve this. In the second, you'd notice parts of the story text floating on the right of the image, this also shouldn't be. There are a few more instances where something isn't right, please look into these.

### Summary
This is really beautiful, you have just a few minor issues to address and you can be on your way! I really commend your efforts and attention to details, congrats :handshake: See you at the top :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by fatymahmed — CHANGES_REQUESTED** [review]
## Hi @MiguelDP4,
Great job making some of the changes 👏👏, However, there's just one more thing that you need to change.
- As mentioned by the previous TSE, for the small screen, the sign-in button in the navigation is colliding with the logo, please resolve this. You could reduce the font size so that they can fit (for the small screen).

### Kindly make this change and request for another code review.
### Status: Changes Required
Feel free to reach out to me on slack (Fatima) if you have any questions, I'd be happy to help.

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @MiguelDP4      
#### Great Job so far, but just one more thing to do . 
- [ ] The content is overlapping the img ,Pleae fix this error.[**Mobile View**]



### Make changes and submit another code review request.
*Happy coding*

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
## Hi team!
### Nice job! Project looks! :+1: 

## Status [Approved]

Thank you for doing all the changes  :1st_place_medal: 



#### Go ahead and merge to master.
#### Goodluck in your next project Happy coding

**Review by Anna-Myzukina — APPROVED** [review]

**Pull request merged**
